Lay the foundation for detect

diff --git a/sl-pkg b/sl-pkg
--- a/sl-pkg
+++ b/sl-pkg
@@ -4,12 +4,15 @@ START_PWD=$(pwd)
 DRY_RUN=false
 HAS_SPECIFIED_COMMAND=false
 COMMAND=
-CACHE_DIR="$HOME/.cache/sl-pkg"
+CACHE_DIR=.
+USR_CACHE_DIR=.
 DOWNLOAD_AND_BUILD=false
 RUN_HELP=false
 CONFIGFILE=/etc/sl-pkg.conf
 PACKAGES=()
 MIRROR=.
+PACKAGES_DB=packages.db
+VERSION=0.0.0
 export MAKEFLAGS="-j$(nproc)"
 
 print_help() {
@@ -72,6 +75,9 @@ download_pkg() {
     fi
   else
     curl -O $URL
+    for PATCH in ${PATCHES[@]}; do
+      curl -O $PATCH
+    done
     if [ $? -ne 0 ]; then
       echo "error: failed to download package $1"
       return 1
@@ -81,10 +87,15 @@ download_pkg() {
 
 build_pkg() {
   if [ $VERSION = "git" ]; then
-    cd $PKG
+    cd $NAME
   else
-    tar xf $PKG-$VERSION.tar* 
-    cd $PKG-$(cut -d"-" -f1 <<<$VERSION)/
+    tar xf $NAME-$VERSION.tar* 
+    cd $NAME-$VERSION ||
+      cd $NAME-$(cut -d"-" -f1 <<<$VERSION)/
+    if [ $? -ne 0 ]; then
+      echo "error: unsupported naming scheme detected"
+      return 1
+    fi
   fi
   prepare || return 1
   build || return 1
@@ -96,12 +107,14 @@ download_cmd() {
     return 1
   fi
   for PKG in ${PACKAGES[@]}; do
-    cd $CACHE_DIR
+    cd $USR_CACHE_DIR
     get_pkginfo $PKG || return 1
     source PACKAGE
     cd $START_PWD
-    download_pkg $PKG || return 1
-    build_pkg || return 1
+    download_pkg || return 1
+    if [ $DOWNLOAD_AND_BUILD = "true" ]; then
+      build_pkg || return 1
+    fi
   done
   cd $START_PWD
   return 0
@@ -169,6 +182,10 @@ case $COMMAND in
   download)
     download_cmd
     exit $?
+    ;;
+  version)
+    echo "sl-pkg $VERSION"
+    exit 0
     ;;
   *)
     echo "error: no command specified"
